# Generated by Django 2.2.5 on 2019-09-02 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190902_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='approve_comment',
            new_name='approved_comment',
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 16, 46, 22, 931329, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 16, 46, 22, 931329, tzinfo=utc)),
        ),
    ]
